### ISSUE TITLE
Mails saved in webspace instead of DB

### ISSUE THREAD

**Issue by rm-medienagentur** [FriendsOfShopware/FroshMailArchive#10]
Is it possible to save the Mails and attachments in folders of the webspace instead of tables in the database? The tables "s_plugin_tinectmailarchive" and "s_plugin_tinectmailarchive_attachments" are getting bigger than 1GB in my case - most hosters officially just support smaller databases.

**Comment by shyim** [comment]
Hey,

I will close this as we currently want to work for features only for Shopware 6. If you want to implement it by own feel free to create pull request
