### ISSUE TITLE
Automatismus zum Löschen älterer Einträge

### ISSUE THREAD

**Issue by pumpger** [FriendsOfShopware/FroshMailArchive#13]
### Please describe the feature you would like to see implemented.

Hallo,
das Archiv wächst mit der Zeit ziemlich an, wenn es nicht hin und wieder händig gelöscht wird. 

Wäre es eventuell machbar, ältere Einträge nach bestimmter Zeit automatisch löschen zu lassen?

Viele Grüße
Armin

**Comment by tinect** [comment]
Hey, danke für die Nachricht. Die Idee kam schon auf.

Wir konzentrieren uns auf die Entwicklung bei Shopware 6. Pull Requests sind willkommen :-)
vgl. https://github.com/FriendsOfShopware/FroshMailArchive/issues/6#issuecomment-868997663
