### ISSUE TITLE
Merge with Mailcatcher?

### ISSUE THREAD

**Issue by buddhaCode** [FriendsOfShopware/FroshMailArchive#2]
Why do you maintain 2 plugins with nearly the same functionality? Both plugins save and display mails. The only difference is passing the mails or catching them. Isn't it better to make config options for this little difference?

**Comment by tinect** [comment]
Hey,
Thank you for contacting. Currently, we don't like to "merge" the plugins, cause they are doing different things for complete different scenarios and needs.
Short explaination: MailCatcher is JUST for not-production-mode,

**Comment by hlohaus** [comment]
Little bit Copy And Paste

**Comment by shyim** [comment]
I guess its not necessary anymore
