### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by powbtr** [FriendsOfShopware/FroshMailArchive#3]
How can i make FroshMailArchive work?

1. Installed
2. activated
3. cleared completed cache
4. tried the "forget password mail" from you example

No entries in the interface

**Comment by tinect** [comment]
Should be correct. You're sure the mail has been sent?

**Comment by powbtr** [comment]
Yes recieved the password-forgot-Mail, but still no entries in the plugin.
Same thing at register-Mails.

**Comment by tinect** [comment]
is there any other plugin/programming for e-mails you've installed? Can't catch any problems while using shopware-mail-way.

**Comment by powbtr** [comment]
yes, i wrote a plugin to handle several requirements regarding on emailsending like cc-reciever and custom attachments

**Comment by tinect** [comment]
You're using Enlight_Components_Mail to send the mails?

**Comment by powbtr** [comment]
Hi @tinect, i use Zend_Mail:
$this->mail = Shopware()->TemplateMail()->createMail($mailType, $this->mailContext, $shop);

**Comment by tinect** [comment]
Hi @powbtr 
createMail returns Enlight_Components_Mail
So that's correct usage.

Do you have an subscription onto `Enlight_Components_Mail_Send` with priority of 9999 or higher?

**Comment by powbtr** [comment]
Thank you very much for the great support!
The Problem was solved by several changes in the AWS-Loadbalancer.

It works great!
