### ISSUE TITLE
scheduled erase option

### ISSUE THREAD

**Issue by rm-medienagentur** [FriendsOfShopware/FroshMailArchive#6]
Feature idea: Automatic erase of (certain) mails older than XX days via cronjob.

**Comment by shyim** [comment]
Maybe instead deleting we could archive it.
Createing a zip file in /files/ where the eml files are compressed

**Comment by tinect** [comment]
I like both ideas :-)

**Comment by yubase** [comment]
Are you planning to develop this enhancement?

**Comment by shyim** [comment]
Hey,

I will close this as we currently want to work for features only for Shopware 6. If you want to implement it by own feel free to create pull request
