### ISSUE TITLE
Das Plugin erzeugt in dem Plugin Pickware WMS Fehlermeldungen

### ISSUE THREAD

**Issue by tocke-hh** [FriendsOfShopware/FroshMailArchive#8]
Das Plugin erzeugt in dem Plugin Pickware WMS Fehlermeldungen

**Comment by tinect** [comment]
Bitte hierzu entsprechende Details, wie Fehlermeldung, zukommen lassen.

Vielen Dank.

**Comment by tocke-hh** [comment]
[cid:image001.png@01D55802.FCD16D60]

Mit freundlichen Grüßen
Christian Tocke

Hans Hagemann GmbH & Co. KG Textilwerk
Eichendorffallee 90
D-48607 Ochtrup

www.hagemann.net<http://www.hagemann.net>
www.3d-print.net<http://www.3d-print.net>
www.zaundruck.de<http://www.zaundruck.de>

Telefon: 02553 / 922-113
Telefax: 02553 / 922-126
Email: tocke@hagemann.net<mailto:tocke@hagemann.net>

Angaben gemäß § 35a GmbHG:
Rechtsform: Kommanditgesellschaft mit Sitz in Ochtrup, HRA Steinfurt 1383
Persönlich haftende Gesellschafterin ist die Hagemann Beteiligungsgesellschaft mbH Registergericht HRB 1101.
Geschäftsführer: Dirk Hagemann, Frank Hagemann

Von: tinect [mailto:notifications@github.com]
Gesendet: Mittwoch, 21. August 2019 09:24
An: FriendsOfShopware/FroshMailArchive <FroshMailArchive@noreply.github.com>
Cc: Tocke Christian <Tocke@hagemann.net>; Author <author@noreply.github.com>
Betreff: Re: [FriendsOfShopware/FroshMailArchive] Das Plugin erzeugt in dem Plugin Pickware WMS Fehlermeldungen (#8)


Bitte hierzu entsprechende Details, wie Fehlermeldung, zukommen lassen.

Vielen Dank.

**Comment by tinect** [comment]
Leider kam das Bild nicht in GitHub an. Vllt. probieren Sie einmal einen Upload im Thread.

**Comment by tocke-hh** [comment]
https://ibb.co/2s3YgNL

**Comment by tinect** [comment]
Hey @tocke-hh,

vielen Dank. Hotfix ist unterwegs.

Viele Grüße

**Comment by tinect** [comment]
Hallo @tocke-hh 
Hatte es geklappt mit dem Update des Plugins?

Viele Grüsse

**Comment by tocke-hh** [comment]
Ja. Danke für den super schnellen Support!
